diploma
horseinthesky/gophkeeper pull request #1
Opened 2023-02-01 17:07 UTC by horseinthesky

В `Makefile` много вспомогательных штук, имеющих говорящие (я надеюсь) сами за себя названия, для автогенерации кода для работы с базой данных через `sqlc` и кода для работы клиента/сервера по gRPC через `protoc`.

Решил делать клиента "интерактивным", т.е. не как запускаемую раз за разом утилиту (навроде awc/gpc клиентов), а работающим постоянно (до выключения пользователем) и синхронизироющим секреты в локальную базу, чтобы обеспечить сценарий, когда у клиента нет связи с сервером (интернет отключили), но пользователь всё ещё хочет смотреть/редактировать свои секреты.

Таблицы секретов на клиенте и сервере совершенно одинаковы, чтобы максимизаровать переиспользование кода для работы сбазой. На сервере есть ещё таблица пользователей.

Пока и клиент и сервер используют postgres для хранения секретов. Пока не знаю, буду ли переделывать. Наверное стоит потом сделать на клиенте `sqlite3`, чтобы не обременять пользователя разворачиванием базы.

Пока клиент в фоне занимается синхронизацией секретов, пользователь работает со своими секретами посредством TUI (делаю через `bubbletea`).

2023-02-04 21:22 UTC, kilchik requested changes

2023-02-04 21:22 UTC, kilchik commented on client/sync.go
> +		localSecret, err := c.storage.GetSecret(
Тут оптимальней конечно забрать все секреты из базы в память и по ним сравнивать, но с учетом того, что это на клиенте, можно наверное оставить

2023-02-04 21:22 UTC, kilchik commented on client/tui.go
> +				m.goph.SetSecret(context.Background(), SecretKind(kind), data[1], []byte(data[2]))
Тут не нужна проверка `len(data) > 1`?

2023-02-04 21:22 UTC, kilchik commented on server/clean.go
> +	deletedSecrets, err := s.storage.CleanSecrets(ctx)
Тут конечно на подумать есть много интересных кейсов
- на первом клиенте удалили секрет, на втором тот же секрет проапдейтили
- добавили секреты с одним ключом сразу на двух клиентах без сети
- локально добавили секрет, а с сервера еще не успело обработаться сообщение с тем же ключом на удаление

Для всех таких кейсов используют версионирование, т е у каждого ключа есть монотонно возрастающая версия, и сервер и клиент по номеру версии определяют, какое обновление более актуально, при полной синхронизации версии секретов на всех клиентах и сервере должны быть одинаковы. 
Если останется время, будет полезно реализовать

2023-02-04 21:22 UTC, kilchik commented on client/client.go
> +	c.runShell(ctx)
Получается, что клиент даже при работающей сети даст возможность пользователю искать секреты до того, как он их загрузил с сервера, я бы тут предложил сделать один раз синхронизацию, потом runShell. Ну а в фоне уже запустить повторяющуюся синхронизацию

2023-02-04 21:22 UTC, kilchik commented on client/client.go
> +	conn, err := grpc.Dial(cfg.Address, grpc.WithTransportCredentials(insecure.NewCredentials()))
SSL

2023-02-04 21:22 UTC, kilchik commented on server/rpc_secrets.go
> +	for _, pbSecret := range in.Secrets {
Тут все-таки стоит переделать работу с базой. Сейчас на N секретов в запросе будет N запросов на SELECT, хотя одного было бы достаточно. Более того я бы предложил объединить запросы на INSERT и MarkSecretDeleted. Выглядит так, что достаточно 3х sql запросов + запросы на UpdateSecret

2023-02-04 21:22 UTC, kilchik commented on client/tui.go
> +				m.goph.SetSecret(context.Background(), SecretKind(kind), data[1], []byte(data[2]))
Так а мы тут никак сикреты не обфусцируем/шифруем? В plain text точно не стоит хранить а базе

2023-02-14 14:12 UTC, horseinthesky commented on client/tui.go
> +				m.goph.SetSecret(context.Background(), SecretKind(kind), data[1], []byte(data[2]))
Тут полностью переделал логику ввода данных секрета . Теперь всё делается через `bubbletea` формы.

2023-02-14 14:13 UTC, horseinthesky commented on client/client.go
> +	c.runShell(ctx)
Сделал первый синк блокирующим до старта TUI. Если нет соединения с сервером, загружаются серверы из локальной базы.

2023-02-14 14:17 UTC, horseinthesky commented on client/client.go
> +	conn, err := grpc.Dial(cfg.Address, grpc.WithTransportCredentials(insecure.NewCredentials()))
Добавил TSL шифрование в обе стороны. Не успел сделать так, чтобы client/server можно было запускать откуда угодно, сейчас работают только из корня проекта.
Хотел сделать embed.FS с директорией ключей, но передаче FS в другой пакет доступ к файлам секретов теряется. Т.е. он (компилятор) не встраивает директорию в бинарь, а всё равно использует пути файловой системы. Я не успел разобраться, как это работает.

2023-02-14 14:18 UTC, horseinthesky commented on client/tui.go
> +				m.goph.SetSecret(context.Background(), SecretKind(kind), data[1], []byte(data[2]))
Не успел сделать шифрование. Данные секретов хранятся в JSON, сериализованном в `[]byte`.

2023-02-14 19:52 UTC, horseinthesky commented on client/client.go
> +	conn, err := grpc.Dial(cfg.Address, grpc.WithTransportCredentials(insecure.NewCredentials()))
Насколько я вижу, моя идея встраивать сертификаты в бинарь была не особенно здравой.

Для работы в production на одном уровне с сервером/клиентом должна быть директория `certs` со всеми сертификатами.

2023-02-14 21:18 UTC, horseinthesky commented
Дописал основной функционал: синхронизация, очистка секретов; TLS в обе стороны; TUI; readme.
Добавил тесты на всё, кроме клиента.

2023-02-15 20:20 UTC, horseinthesky commented
Добавил тесты клиент.

2023-02-16 19:12 UTC, horseinthesky commented
Добавил шифрование секретов.

2023-02-19 18:04 UTC, kilchik approved these changes

2023-02-19 18:04 UTC, kilchik commented on server.go
> +func main() {
Двух функций main в одном пакете быть не должно, client.go и server.go надо перенести в cmd/client и cmd/server - в сообществе Go уже устоялось мнение о том, где искать входную точку в приложение.
Ну и конечно остальные пакеты я бы тоже советовал разнести по /pkg/, /internal/pkg/, например, /internal/pkg/client и /internal/pkg/server

2023-02-21 16:32 UTC, merged